### ISSUE TITLE
Unsupported 5.0 version

### ISSUE THREAD

**Issue by 0xDeve** [Drakynfly/HeartGraph#16]
Hey,
I really like your plugin from what I have seen so far. Is there a version for ue 5.0 or is it ue 5.0 supported? Im having quite some compile issues with 5.0.3 atm, a lot of syntax differences too. 

Thanks a lot!

**Comment by Drakynfly** [comment]
Unfortunately, I cannot easily support 5.0, since FInstancedStruct only got blueprint support as of 5.1. This means that everything that currently uses FInstancedStructs are broken where they get exposed to blueprints, notably: Pin types, and NodeTree types.
If you just wanted to hack things into working, you would have to remove the blueprint support for these things yourself, and add replacements/do everything in c++.
